//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioAlmacen.Base_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Vendedor
    {
        public int codvendedor { get; set; }
        public string nmvendedor { get; set; }
        public string tlvendedor { get; set; }
        public string drvendedor { get; set; }
    }
}
