//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioAlmacen.Base_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Cliente
    {
        public int codclient { get; set; }
        public string nmclient { get; set; }
        public string tlclient { get; set; }
        public string drclient { get; set; }
    }
}
