//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioAlmacen.Base_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROYECTO_INVENTARIOEntities4 : DbContext
    {
        public PROYECTO_INVENTARIOEntities4()
            : base("name=PROYECTO_INVENTARIOEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detalle_Cliente> Detalle_Cliente { get; set; }
        public virtual DbSet<Detalle_Vendedor> Detalle_Vendedor { get; set; }
        public virtual DbSet<Productos_Detalle> Productos_Detalle { get; set; }
    }
}
