//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioAlmacen.Base_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_Detalle
    {
        public int prodcodigo { get; set; }
        public string prodnombre { get; set; }
        public int prodcantidad { get; set; }
        public string proddescripcion { get; set; }
        public decimal prodprecio { get; set; }
        public string prodmarca { get; set; }
    }
}
